import type { SeekerListing } from "@/components/SeekerPropertyCard";

export const SEEKER_LISTINGS: SeekerListing[] = [
  {
    id: "b1",
    title: "3-Bedroom Flat, Lekki Phase 1",
    location: "Lekki Phase 1, Lagos",
    price: "₦2,800,000",
    priceSuffix: "/yr",
    tag: "FOR SALE",
    sqft: "3500 sqft",
    beds: 3,
    baths: 4,
    image: "/images/prop1.jpg",
    amenities: ["Newly Built", "C of O", "Only on RentBuyStay", "Parking", "Air Conditioning"],
    seller: { name: "Emeka Nwafor", initials: "EN", verified: true },
    description:
      "A very beautiful 3 bedroom flat with state-of-the-art facilities located in a serene estate in Lekki Phase 1, Lagos for sale ...",
    listedOn: "27 Mar 2026",
    galleryCount: 3,
    lat: 6.4400,
    lng: 3.4500,
  },
  {
    id: "b2",
    title: "2-Bedroom Apartment, Victoria Island",
    location: "Victoria Island, Lagos",
    price: "₦450,000",
    priceSuffix: "/night",
    tag: "FOR RENT",
    sqft: "1800 sqft",
    beds: 3,
    baths: 2,
    image: "/images/prop2.jpg",
    amenities: ["Newly Built", "24/7 Security", "Furnished", "Swimming Pool", "Internet/WiFi"],
    seller: { name: "Dare Okoye", initials: "DO", verified: true, avatarUrl: "/images/seekers/dare-okoye.png" },
    lat: 6.4280,
    lng: 3.4220,
  },
  {
    id: "b3",
    title: "2-Bedroom Flat, Jibowu, Yaba",
    location: "Yaba, Lagos",
    price: "₦1,800,000",
    priceSuffix: "/yr",
    tag: "SHORTLET",
    sqft: "2000 sqft",
    beds: 3,
    baths: 3,
    image: "/images/prop5.jpg",
    amenities: ["Newly Built", "24/7 Security", "Borehole Water", "Internet/WiFi", "Tiled Floor"],
    seller: { name: "Aishat Dada", initials: "AD", verified: true, avatarUrl: "/images/seekers/aishat-dada.png" },
    lat: 6.5170,
    lng: 3.3700,
  },
  {
    id: "b4",
    title: "Office Space, Ikeja GRA",
    location: "Ikeja GRA, Lagos",
    price: "₦3,400,000",
    priceSuffix: "/yr",
    tag: "FOR RENT",
    sqft: "1200 sqft",
    beds: 2,
    baths: 1,
    image: "/images/prop3.jpg",
    amenities: ["Newly Built", "24/7 Security", "Backup Generator", "High Speed Internet"],
    seller: { name: "Stanley Alabi", initials: "SA", verified: true },
    lat: 6.5900,
    lng: 3.3500,
  },
  {
    id: "b5",
    title: "4-bedroom Duplex, Ikoyi",
    location: "Ikoyi, Lagos",
    price: "₦260,000,000",
    tag: "FOR SALE",
    sqft: "5000 sqft",
    beds: 5,
    baths: 6,
    image: "/images/prop4.jpg",
    amenities: ["Newly Built", "24/7 Security", "Swimming Pool", "Smart Home", "Gym Facility"],
    seller: { name: "Kenni Olaoye", initials: "KO", verified: true },
    lat: 6.4500,
    lng: 3.4400,
  },
  {
    id: "b6",
    title: "Luxury Penthouse, Eko Atlantic",
    location: "Eko Atlantic City, Lagos",
    price: "₦1,200,000,000",
    tag: "SHORTLET",
    sqft: "4200 sqft",
    beds: 4,
    baths: 5,
    image: "/images/prop1.jpg",
    amenities: ["Newly Built", "24/7 Security", "Swimming Pool", "Gym", "Smart Home"],
    seller: { name: "Gabriel Okechukwu", initials: "GO", verified: true },
    lat: 6.4170,
    lng: 3.4040,
  },
  {
    id: "b7",
    title: "1-Bedroom Serviced Apartment, Oniru",
    location: "Oniru Estate, Lagos",
    price: "₦160,000",
    priceSuffix: "/night",
    tag: "FOR RENT",
    sqft: "560 sqft",
    beds: 2,
    baths: 1,
    image: "/images/prop2.jpg",
    amenities: ["Newly Built", "24/7 Security", "Furnished", "Air Conditioning"],
    seller: { name: "Olaide Batifeori", initials: "OB", verified: true, avatarUrl: "/images/seekers/olaide-batifeori.png" },
    lat: 6.4350,
    lng: 3.4380,
  },
  {
    id: "b8",
    title: "2-Bedroom Flat, Surulere",
    location: "Surulere, Lagos",
    price: "₦175,000",
    priceSuffix: "/month",
    tag: "FOR RENT",
    sqft: "1450 sqft",
    beds: 2,
    baths: 2,
    image: "/images/prop5.jpg",
    amenities: ["24/7 Security", "Borehole Water", "Tiled Floor", "Parking"],
    seller: { name: "Chioma Eze", initials: "CE", verified: true },
    lat: 6.5000,
    lng: 3.3580,
  },
  {
    id: "b9",
    title: "4-Bedroom Apartment, Magodo Phase 1",
    location: "Magodo, Lagos",
    price: "₦11,500,000",
    tag: "FOR SALE",
    sqft: "2800 sqft",
    beds: 4,
    baths: 4,
    image: "/images/prop4.jpg",
    amenities: ["Newly Built", "24/7 Security", "Swimming Pool", "Gated Estate"],
    seller: { name: "Bayo Lawal", initials: "BL", verified: true },
    lat: 6.6200,
    lng: 3.3850,
  },
  {
    id: "b10",
    title: "3-Bedroom Flat, Ikeja",
    location: "Ikeja, Lagos",
    price: "₦4,500,000",
    priceSuffix: "/yr",
    tag: "FOR RENT",
    sqft: "2200 sqft",
    beds: 3,
    baths: 3,
    image: "/images/prop3.jpg",
    amenities: ["24/7 Security", "Parking", "Tiled Floor", "Borehole Water"],
    seller: { name: "Tunde Adekola", initials: "TA", verified: true },
    lat: 6.6010,
    lng: 3.3510,
  },
  {
    id: "b11",
    title: "5-Bedroom Mansion, Banana Island",
    location: "Banana Island, Lagos",
    price: "₦950,000,000",
    tag: "FOR SALE",
    sqft: "8500 sqft",
    beds: 5,
    baths: 7,
    image: "/images/prop4.jpg",
    amenities: ["Newly Built", "24/7 Security", "Swimming Pool", "Gym", "Smart Home", "Cinema"],
    seller: { name: "Lara Bello", initials: "LB", verified: true },
    lat: 6.4290,
    lng: 3.4480,
  },
  {
    id: "b12",
    title: "2-Bedroom Apartment, Lekki Phase 2",
    location: "Lekki Phase 2, Lagos",
    price: "₦220,000",
    priceSuffix: "/night",
    tag: "SHORTLET",
    sqft: "1500 sqft",
    beds: 2,
    baths: 2,
    image: "/images/prop2.jpg",
    amenities: ["Newly Built", "24/7 Security", "Furnished", "Pool"],
    seller: { name: "Ifeanyi Obi", initials: "IO", verified: true },
    lat: 6.4280,
    lng: 3.5300,
  },
];

export function getSeekerListing(id: string): SeekerListing | undefined {
  return SEEKER_LISTINGS.find((l) => l.id === id);
}
